// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: content.proto

package content_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContentServiceClient is the client API for ContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentServiceClient interface {
	// Journal
	CreateJournal(ctx context.Context, in *CreateJournalReq, opts ...grpc.CallOption) (*Journal, error)
	GetJournal(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Journal, error)
	GetJournalList(ctx context.Context, in *GetList, opts ...grpc.CallOption) (*GetJournalListRes, error)
	UpdateJournal(ctx context.Context, in *Journal, opts ...grpc.CallOption) (*Journal, error)
	DeleteJournal(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Edition
	CreateEdition(ctx context.Context, in *CreateEditionReq, opts ...grpc.CallOption) (*Edition, error)
	GetEdition(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Edition, error)
	GetEditionList(ctx context.Context, in *GetEditionListReq, opts ...grpc.CallOption) (*GetEditionListRes, error)
	UpdateEdition(ctx context.Context, in *Edition, opts ...grpc.CallOption) (*Edition, error)
	DeleteEdition(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Countries and cities
	GetCountryList(ctx context.Context, in *GetCountryListReq, opts ...grpc.CallOption) (*GetCountryListRes, error)
	GetCityList(ctx context.Context, in *GetCityListReq, opts ...grpc.CallOption) (*GetCityListRes, error)
}

type contentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentServiceClient(cc grpc.ClientConnInterface) ContentServiceClient {
	return &contentServiceClient{cc}
}

func (c *contentServiceClient) CreateJournal(ctx context.Context, in *CreateJournalReq, opts ...grpc.CallOption) (*Journal, error) {
	out := new(Journal)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/CreateJournal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetJournal(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Journal, error) {
	out := new(Journal)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/GetJournal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetJournalList(ctx context.Context, in *GetList, opts ...grpc.CallOption) (*GetJournalListRes, error) {
	out := new(GetJournalListRes)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/GetJournalList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateJournal(ctx context.Context, in *Journal, opts ...grpc.CallOption) (*Journal, error) {
	out := new(Journal)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/UpdateJournal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) DeleteJournal(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/DeleteJournal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) CreateEdition(ctx context.Context, in *CreateEditionReq, opts ...grpc.CallOption) (*Edition, error) {
	out := new(Edition)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/CreateEdition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetEdition(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Edition, error) {
	out := new(Edition)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/GetEdition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetEditionList(ctx context.Context, in *GetEditionListReq, opts ...grpc.CallOption) (*GetEditionListRes, error) {
	out := new(GetEditionListRes)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/GetEditionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateEdition(ctx context.Context, in *Edition, opts ...grpc.CallOption) (*Edition, error) {
	out := new(Edition)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/UpdateEdition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) DeleteEdition(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/DeleteEdition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetCountryList(ctx context.Context, in *GetCountryListReq, opts ...grpc.CallOption) (*GetCountryListRes, error) {
	out := new(GetCountryListRes)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/GetCountryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetCityList(ctx context.Context, in *GetCityListReq, opts ...grpc.CallOption) (*GetCityListRes, error) {
	out := new(GetCityListRes)
	err := c.cc.Invoke(ctx, "/content_service.ContentService/GetCityList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServiceServer is the server API for ContentService service.
// All implementations must embed UnimplementedContentServiceServer
// for forward compatibility
type ContentServiceServer interface {
	// Journal
	CreateJournal(context.Context, *CreateJournalReq) (*Journal, error)
	GetJournal(context.Context, *PrimaryKey) (*Journal, error)
	GetJournalList(context.Context, *GetList) (*GetJournalListRes, error)
	UpdateJournal(context.Context, *Journal) (*Journal, error)
	DeleteJournal(context.Context, *PrimaryKey) (*emptypb.Empty, error)
	// Edition
	CreateEdition(context.Context, *CreateEditionReq) (*Edition, error)
	GetEdition(context.Context, *PrimaryKey) (*Edition, error)
	GetEditionList(context.Context, *GetEditionListReq) (*GetEditionListRes, error)
	UpdateEdition(context.Context, *Edition) (*Edition, error)
	DeleteEdition(context.Context, *PrimaryKey) (*emptypb.Empty, error)
	// Countries and cities
	GetCountryList(context.Context, *GetCountryListReq) (*GetCountryListRes, error)
	GetCityList(context.Context, *GetCityListReq) (*GetCityListRes, error)
	mustEmbedUnimplementedContentServiceServer()
}

// UnimplementedContentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContentServiceServer struct {
}

func (UnimplementedContentServiceServer) CreateJournal(context.Context, *CreateJournalReq) (*Journal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJournal not implemented")
}
func (UnimplementedContentServiceServer) GetJournal(context.Context, *PrimaryKey) (*Journal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJournal not implemented")
}
func (UnimplementedContentServiceServer) GetJournalList(context.Context, *GetList) (*GetJournalListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJournalList not implemented")
}
func (UnimplementedContentServiceServer) UpdateJournal(context.Context, *Journal) (*Journal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJournal not implemented")
}
func (UnimplementedContentServiceServer) DeleteJournal(context.Context, *PrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJournal not implemented")
}
func (UnimplementedContentServiceServer) CreateEdition(context.Context, *CreateEditionReq) (*Edition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEdition not implemented")
}
func (UnimplementedContentServiceServer) GetEdition(context.Context, *PrimaryKey) (*Edition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdition not implemented")
}
func (UnimplementedContentServiceServer) GetEditionList(context.Context, *GetEditionListReq) (*GetEditionListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEditionList not implemented")
}
func (UnimplementedContentServiceServer) UpdateEdition(context.Context, *Edition) (*Edition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEdition not implemented")
}
func (UnimplementedContentServiceServer) DeleteEdition(context.Context, *PrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEdition not implemented")
}
func (UnimplementedContentServiceServer) GetCountryList(context.Context, *GetCountryListReq) (*GetCountryListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountryList not implemented")
}
func (UnimplementedContentServiceServer) GetCityList(context.Context, *GetCityListReq) (*GetCityListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCityList not implemented")
}
func (UnimplementedContentServiceServer) mustEmbedUnimplementedContentServiceServer() {}

// UnsafeContentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentServiceServer will
// result in compilation errors.
type UnsafeContentServiceServer interface {
	mustEmbedUnimplementedContentServiceServer()
}

func RegisterContentServiceServer(s grpc.ServiceRegistrar, srv ContentServiceServer) {
	s.RegisterService(&ContentService_ServiceDesc, srv)
}

func _ContentService_CreateJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJournalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/CreateJournal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateJournal(ctx, req.(*CreateJournalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/GetJournal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetJournal(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetJournalList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetJournalList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/GetJournalList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetJournalList(ctx, req.(*GetList))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Journal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/UpdateJournal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateJournal(ctx, req.(*Journal))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_DeleteJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).DeleteJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/DeleteJournal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).DeleteJournal(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_CreateEdition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEditionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateEdition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/CreateEdition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateEdition(ctx, req.(*CreateEditionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetEdition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetEdition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/GetEdition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetEdition(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetEditionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEditionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetEditionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/GetEditionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetEditionList(ctx, req.(*GetEditionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateEdition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Edition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateEdition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/UpdateEdition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateEdition(ctx, req.(*Edition))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_DeleteEdition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).DeleteEdition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/DeleteEdition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).DeleteEdition(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetCountryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetCountryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/GetCountryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetCountryList(ctx, req.(*GetCountryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetCityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCityListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetCityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content_service.ContentService/GetCityList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetCityList(ctx, req.(*GetCityListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentService_ServiceDesc is the grpc.ServiceDesc for ContentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content_service.ContentService",
	HandlerType: (*ContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJournal",
			Handler:    _ContentService_CreateJournal_Handler,
		},
		{
			MethodName: "GetJournal",
			Handler:    _ContentService_GetJournal_Handler,
		},
		{
			MethodName: "GetJournalList",
			Handler:    _ContentService_GetJournalList_Handler,
		},
		{
			MethodName: "UpdateJournal",
			Handler:    _ContentService_UpdateJournal_Handler,
		},
		{
			MethodName: "DeleteJournal",
			Handler:    _ContentService_DeleteJournal_Handler,
		},
		{
			MethodName: "CreateEdition",
			Handler:    _ContentService_CreateEdition_Handler,
		},
		{
			MethodName: "GetEdition",
			Handler:    _ContentService_GetEdition_Handler,
		},
		{
			MethodName: "GetEditionList",
			Handler:    _ContentService_GetEditionList_Handler,
		},
		{
			MethodName: "UpdateEdition",
			Handler:    _ContentService_UpdateEdition_Handler,
		},
		{
			MethodName: "DeleteEdition",
			Handler:    _ContentService_DeleteEdition_Handler,
		},
		{
			MethodName: "GetCountryList",
			Handler:    _ContentService_GetCountryList_Handler,
		},
		{
			MethodName: "GetCityList",
			Handler:    _ContentService_GetCityList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content.proto",
}
